config/routes.rb
Rails.application.routes.draw do
  resources :users do
    collection do
      get :login
    end
  end

  namespace :public do
    post '/users/login', to: 'users#login'
  end

  namespace :private do
    post '/users/verify_email', to: 'users#verify_email'
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/

  attr_accessor :image_file

  validates :email, presence: true, format: { with: EMAIL_REGEX }, uniqueness: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/private/users_controller.rb
class Private::UsersController < ActionController::API
  include ActionController::HttpAuthentication::Basic::ControllerMethods

  before_action :set_user
  http_basic_authenticate_with name: ENV['PRIVATE_USERNAME'], password: ENV['PRIVATE_PASSWORD']

  # POST /private/users/verify_email
  def verify_email
    if @user && @user.image == params[:image]
      AuthMailer.success_auth(@email, request.user_agent).deliver_later
      render json: { message: 'OK' }
    else
      AuthMailer.failed_auth(@email, request.user_agent).deliver_later
      render json: { message: 'No Autorizado' }, status: :unauthorized
    end
  end

  private

  def set_user
    @email = params[:email]
    @user = User.find_by(email: @email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:id
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users/:id
  def create
    @user = User.new user_create_params
    if @user.save
      flash.notice = 'User successfully created'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = @user.errors.full_messages
      render :new
    end
  end

  # GET /users/:id/edit
  def edit; end

  # GET /users/login
  def login; end

  # PUT /users/:id
  def update
    if @user.update user_update_params
      flash.notice = 'User successfully updated'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = @user.errors.full_messages
      render :edit
    end
  end

  # DELETE /users/:id
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_create_params
    params.require(:user).permit(:email, :image)
  end

  def user_update_params
    params.require(:user).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageAuth</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="container nav-wrapper">
        <%= link_to 'Image Auth', root_path, class: 'brand-logo' %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to 'Login', login_users_path %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="section">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/edit.html.slim
= form_for @user, html: { id: 'user-form' } do |f|
  .row
    .input-field
      = f.text_field :email, disabled: true
      = f.label :email
    .file-field.input-field
      .btn
        span File
        = f.file_field :image_file
      .file-path-wrapper
        input class="file-path validate" type="text"
  .row.center-align
    button class="btn waves-effect waves-light" type="submit" name="action"
      | Submit
      i class="material-icons right"

app/views/users/index.html.slim
.row
  = link_to 'New User', new_user_path, class: 'waves-effect waves-light btn'

.row.card-container
  - @users.each do |user|
    .card
      .card-image
        = image_tag user.image
      .card-content.center-align
        span class="activator grey-text text-darken-4"
          = link_to user.email, user_path(user)
      .card-action
        = link_to 'Edit', edit_user_path(user)
        = link_to 'Remove', user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }

app/views/users/login.html.slim
form id="login-form"
  .row
    .input-field
      input name="email" id="email" type="text"
      label for="email" Email
    .file-field.input-field
      .btn
        span File
        input type="file" name="image_file" id="image_file"
      .file-path-wrapper
        input class="file-path validate" type="text"
  .row.center-align
    button< class="btn waves-effect waves-light" type="submit" name="action" Login

app/views/users/new.html.slim
= form_for @user, html: { id: 'user-form' } do |f|
  .row
    .input-field
      = f.text_field :email
      = f.label :email
    .file-field.input-field
      .btn
        span File
        = f.file_field :image_file
      .file-path-wrapper
        input class="file-path validate" type="text"
  .row.center-align
    = link_to 'Cancel', users_path, class: 'btn waves-effect waves-light red accent-2'
    button< class="btn waves-effect waves-light" type="submit" name="action" Submit

app/views/users/show.html.slim
p= @user.email
p= image_tag @user.image